### ISSUE TITLE
❓ Question: Reverse share created but not able to view?

### ISSUE THREAD

**Issue by OliPassey** [stonith404/pingvin-share#148]
### 🙋‍♂️ Question

I've sent a reverse share link to a friend, who has created 4 share with files in.
When i copy the link from reverse shares into a browser, i get:
![image](https://user-images.githubusercontent.com/7745805/233371284-856ca863-d2eb-420c-bd61-b44189c05f7c.png)

The URL has a double / in eg - 
https://files.domain.tld//share/validsharename
but removing this also gives the same error.

How can i access these files without asking them to reupload?

**Comment by stonith404** [comment]
That's strange, I can't reproduce this. Are you sure your friend didn't set a visitor limit? If not, please check the logs withj `cd pingvin-share && docker compose logs`. Let me know if you've found anything.

The URL has probably a double slash because you've set your app url to `https://example.com/` instead of `https://example.com`, but this shouldn't make a difference.
