### ISSUE TITLE
🚀 Feature: Update files in an existing share

### ISSUE THREAD

**Issue by OlivierProTips** [stonith404/pingvin-share#154]
### 🔖 Feature description

Add and remove files in an existing share

### 🎤 Pitch

I like sharing multiple files in one share link. And sometimes, I want to add / remove some files in this share. That way, I do not have to generate a new share link. 

So it would be great if we can upload or delete a file from an existing share.

**Comment by pierrbt** [comment]
@OlivierProTips, don't you think that it is easier to just reupload the files you wanted to share, because it would become harder to have a button, to display an whole new page, to reupload new files as a temp share, zip the files again and replace everything. I think this is pretty unnecessary when you just have to reupload things, or just upload all the files the first time.

**Comment by OlivierProTips** [comment]
@pierrbt From my point of view, it adds complexity. For instance, I share a bunch of files, for a project, and I want to update only one file. It is time consuming if I have to delete and send everything back, for only one changed file.

But I understand that it is a lot of works.

For that use case, I think I need a folder sharing system instead. :)

**Comment by IvanLi-CN** [comment]
I think it is necessary to be able to update the file list of existing shared links. For my use case, I wanted to share the list of files and add new files later. Since I will delete these files locally after uploading, without this feature, I need to download all the files and then upload them again, which is very unfriendly.

**Comment by IvanLi-CN** [comment]
I browsed the code, and it seems that the backend only needs to support adding and deleting File schema to achieve this function? I could try submitting a PR for both the front and backends to implement it.

**Comment by stonith404** [comment]
@IvanLi-CN Yeah feel free to create a PR :)
