### ISSUE TITLE
🐛 Bug Report: Docker is not up to date

### ISSUE THREAD

**Issue by pierrbt** [stonith404/pingvin-share#170]
### 👟 Reproduction steps

The version hosted on Docker Hub is not up to date. By example, there is no copy button when the share link is shown. I tried to host the dev version with Next and Nest and it got these updates.

### 👍 Expected behavior

The Docker Hub to have the latest release.

### 👎 Actual Behavior

The Docker Hub don't have the latest release.

### 🌐 Browser

Chrome

**Comment by pierrbt** [comment]
Well I might make a mistake because the version displayed is 0.15.0. Well close this issue if you think this is inappropriate but I'm disappointed, the copy button isn't displayed here (I talk about that because that's on what I've worked on in a PR) : 

![image](https://github.com/stonith404/pingvin-share/assets/83456236/4277cf7b-b6e4-4973-bb6e-0206a61a930e)
![image](https://github.com/stonith404/pingvin-share/assets/83456236/47bad950-ab21-45cb-b734-958079e9d03d)

**Comment by stonith404** [comment]
That is actually on purpose. The button only is shown if `window.isSecureContext` is true ([see in the code](https://github.com/stonith404/pingvin-share/blob/main/frontend/src/components/upload/modals/showCompletedUploadModal.tsx#L38)). This check is required because copying to clipboard doesn't work if `window.isSecureContext` is false

[MDM docs](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard):
> Secure context: This feature is available only in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) (HTTPS), in some or all [supporting browsers](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard#browser_compatibility). 

The most common reason that `isSecureContext` is false is if you're not using https. Might this be the issue?

**Comment by pierrbt** [comment]
Oh yes I've not activated HTTPS yet, but this is to avoid multiple others request on unsecurised connections to avoid sniffing or why ?
