### ISSUE TITLE
🐛 Bug Report: Zip files get zipped again

### ISSUE THREAD

**Issue by webysther** [stonith404/pingvin-share#187]
### 👟 Reproduction steps

- upload a zip file
- after upload the same file get zipped again

### 👍 Expected behavior

detected if the file is a compressed format (zip, 7z, gz) and keep the file untouched.

### 👎 Actual Behavior

zip the same file again

### 🌐 Browser

Chrome

**Comment by pierrbt** [comment]
The only case that would be useful is when there is only one file in the .zip format (because the app must send it always in zip to be consistent). It may be interesting if someone wants to share one big zip file. This would save a bit of disk usage.
Would you be interested in trying to make this feature ?

**Comment by webysther** [comment]
> The only case that would be useful is when there is only one file in the .zip format (because the app must send it always in zip to be consistent). It may be interesting if someone wants to share one big zip file. This would save a bit of disk usage. Would you be interested in trying to make this feature ?

Yeap, I will look further, just need to finish the homelab setup first

**Comment by webysther** [comment]
i think this become a minor since zip compression level is available.
