### ISSUE TITLE
Direct link to file

### ISSUE THREAD

**Issue by Smallinger** [stonith404/pingvin-share#21]
A awesome feature that you get a direkt link to the file, so you can post it on discord, steam, forums or what ever.

**Comment by stonith404** [comment]
Hey, yep that would be a nice feature. I'll add it to the next release.

**Comment by stonith404** [comment]
I thought more about your idea but I don't really see a reason for this feature, because you could only upload one file to a share. 
Additionally this would be really difficult for security reasons.
E.g Should the visitor count increase when downloading a file? If yes what if you want to download another file from the same share, should be the visitor count also be increased?

What do you think?

**Comment by W1BTR** [comment]
Definitely think this should be a box that can be checked. I was hoping to be able to create some simple hosting for file downloads in scripts, but cant really use this for this
