### ISSUE TITLE
Reduce docker image size

### ISSUE THREAD

**Issue by stonith404** [stonith404/pingvin-share#30]
Currently the docker image is around 500mb. This should be reduced with better multi stage building.

**Comment by stonith404** [comment]
Already improved the docker image with the use of slim images (d6a88f2a22bd019c213c7c73ebfdf108dfead204), but it could get improved even more.

**Comment by Neyxo** [comment]
Hi Elias
I can take care of that.
Exciting project, by the way!
-jmc

**Comment by stonith404** [comment]
Hey jmc nice to meet you again :) Would be awesome if you could work on that, thank you!

**Comment by Neyxo** [comment]
So I had some time today to improve the Dockerfile. The image size has been reduced from 1.27 GB to 533 MB, and the docker build is faster. PR #37 

What further can be done? (I would not recommend this unless size is a big issue)

-  [78 MB] Remove ts-node from the build by executing Prisma seed while building
   - Due to how Prisma works this is risky
- [~50 MB] Use distroless Node on the final stage
   - Is only possible if installation of "openssl" is not needed
- [~100 MB] Bundling/treeshake backend node_modules
   - Nest.js does not natively support bundling/treeshake
   - Custom Webpack setup needed
