### ISSUE TITLE
🚀 Feature: After creating a share, add an entry to jump to the share page or edit page

### ISSUE THREAD

**Issue by IvanLi-CN** [stonith404/pingvin-share#372]
### 🔖 Feature description

After the sharing is successfully created, the entrance to jump to the editing and sharing page will be added.

in this modal:

<img width="998" alt="image" src="https://github.com/stonith404/pingvin-share/assets/30215105/4eb6bac4-9aeb-4b9c-b9de-e3d2145c732d">

### 🎤 Pitch

Sometimes I want to share some files for myself for sharing and archiving. Then download them on the server immediately. At this point I need:

1. Copy share link
2. Open in new browser tab
3. click copy link buttom

Maybe we can simplify click a button to directly access the file list, making it easier to copy links.

I'd love to open a PR for this feature if you allow it.

**Comment by IvanLi-CN** [comment]
Or just add an edit entry, and then add a copy link button to each list item in the edit file interface?

**Comment by stonith404** [comment]
Yeah that would be nice! In my opinion it would make more sense if we create a button that brings the user to the share page instead of the edit page, like you've suggested initially. 

I have two suggestions where to place that button. The first suggestion would be to add a second icon button besides the copy button. The second would be below the "Done" button. Or maybe you have a better suggestion?

![Screenshot 2024-01-07 at 22 19 27](https://github.com/stonith404/pingvin-share/assets/58886915/6548478e-2b52-4e5f-971c-4a0270bb979c)

**Comment by IvanLi-CN** [comment]
> I have two suggestions where to place that button. The first suggestion would be to add a second icon button besides the copy button. The second would be below the "Done" button. Or maybe you have a better suggestion?

I think ① is a good choice.
