### ISSUE TITLE
🐛 Bug Report: umlaut changing when downloading file

### ISSUE THREAD

**Issue by Craftingcat99** [stonith404/pingvin-share#494]
### 👟 Reproduction steps

upload a .zip file with the letter "ö" in it, it get's displayed correctly, then download

### 👍 Expected behavior

ö should stay ö even when downloaded

### 👎 Actual Behavior

the filename replaces the "ö" with an "ý"

### 🌐 Browser

Firefox

**Comment by stonith404** [comment]
Strange, this bug doesn't occur for me. Which version of Pingvin Share and operating system are you using?

![Screenshot 2024-06-10 at 11 35 53](https://github.com/stonith404/pingvin-share/assets/58886915/75de4182-95c8-4ec5-9626-1b4e330b04a2)

**Comment by stonith404** [comment]
Closing this because there was no response. Feel free to comment if this issue still occurs.

**Comment by MCStreetguy** [comment]
@stonith404 I just stumbled across this issue while encountering the same problem. I'll try to provide the previously requested information for my case:

Pingvin version: v1.11.1 (using Docker with `latest` image) hosted on Ubuntu 20.04.6 LTS
Current operating system where the problem happens is Ubuntu 22.04.3 LTS
The problem occurs on Firefox 137.0.1 as well as Chrome 133.0.6943.98

I don't currently have access to other browsers to test this in, but I'll check to see if this happens on my Windows 10 machine as well and update you accordingly.

You can see this happening in the screenshots below:

![Image](https://github.com/user-attachments/assets/d4e4ee39-b3ec-4654-9677-d2867a37c23b)

![Image](https://github.com/user-attachments/assets/4dba5f63-3d3a-428e-895e-6bd71c9dd1f0)

This also doesn't seem to be the save dialog screwing up the name, as the same faulty filename is already sent in the `Content-Disposition` HTTP response header:

![Image](https://github.com/user-attachments/assets/ffd60ce7-3630-4c21-9ffe-dc8389a73989)

All umlauts get mangled as well as the character `ß` as far as I can tell from my tests so far.
Within the UI everything looks normal, even in the little preview window for media, it only happens when downloading the file.

Also, even though I think it's obvious, the problem doesn't only occur with .zip files but is independent of the type of file. Originally it happened to me with images and videos, I just used the .zip file for testing to pick up on your previous example.
