### ISSUE TITLE
🐛 Bug Report: Page views "my shares".

### ISSUE THREAD

**Issue by ipod86** [stonith404/pingvin-share#570]
### 👟 Reproduction steps

When I create a file share, the counter for access is shown as 0. 

After the first page access, there are immediately 120-140 accesses (sometimes also the second time). After that, it seems to count up properly.

### 👍 Expected behavior

That after the first page view a 1 is shown instead of 120

### 👎 Actual Behavior

It shows between 120 and 130 instead of 1

**Comment by stonith404** [comment]
That's really strange and I can't reproduce it. Can you share a screen recording of how you create and access the share? 

Did you post the link to any platform like Instagram? Because on such platforms there are bots that immediately access and check the links. I doubt that the bots access the share 120 times though.

**Comment by ipod86** [comment]
No, the links are fresh and are never shared. 
Everything stays at 0 until I go to it for the first time. 

What I notice, however, is that the first time you open the page, it takes a long time to see the file. The next time you open it, it appears almost immediately. I made a video. Can I email the link? I would not like to show the URL here.

**Comment by stonith404** [comment]
Thanks for the video.  I think the browser is somehow spamming the API with multiple requests to view the share, which is causing the delay and the high visitor count. Could you please send me a link to a share via email so I can test it myself?

**Comment by stonith404** [comment]
The problem is that you are setting the `cache-control` header to `public, max-age=15, must-revalidate`. Just remove this header or find an appropriate alternative that does invalidate the cache if cookies have changed.

Here’s why this problem occurs:
When you visit the share page, the website attempts to retrieve the share information. If you don’t have a valid token, this request fails. The website then obtains a valid token and tries to retrieve the share again. However, because the initial failed request (due to the missing token) is cached, the website continues to believe you don’t have a valid token, leading it to repeatedly request a new one.

**Comment by ipod86** [comment]
That was it. Thank you. 

I have now deleted the line in the caddy file. 
I saw it online once and added it. Probably doesn't really make sense anyway...

**Comment by stonith404** [comment]
Great :)
