### ISSUE TITLE
🐛 Bug Report: mail field for LDAP users is not saved

### ISSUE THREAD

**Issue by RatCornu** [stonith404/pingvin-share#601]
### 👟 Reproduction steps

- Set up LDAP authentication
- Log in with a LDAP user and set the mail to `test@test.org`
- Logout and login another time
- See `<UUID>@ldap.local` as email

### 👍 Expected behavior

It should keep the mail the user has set, or even better give an option in the admin configuration to read the email field directly from the LDAP

### 👎 Actual Behavior

The mail field for the LDAP users keeps getting replaced by nonsense at each login

### 📜 Logs

```
[Nest] 2408662  - 09/19/2024, 2:06:47 PM   DEBUG [AuthService] Trying LDAP login for user ratcornu
[Nest] 2408662  - 09/19/2024, 2:06:47 PM     LOG [AuthService] Successful LDAP login for user <UUID>@ldap.local from IP <IP>
```

**Comment by stonith404** [comment]
@WolverinDEV The email gets set to a new random email on every login. https://github.com/stonith404/pingvin-share/blob/64acae11a26c700a61be369599975c28508679cc/backend/src/user/user.service.ts#L97-L99

We could just remove this line, because it only needs to be set if the user doesn't exist in the db yet, right?
https://github.com/stonith404/pingvin-share/blob/64acae11a26c700a61be369599975c28508679cc/backend/src/user/user.service.ts#L113


But it would be nice if the email gets mapped from the LDAP, do you think this is difficult to implement?

**Comment by RatCornu** [comment]
If I read the code correctly (I'm not an expert in JS/TS/...), a possible solution would be to create a new field in the configuration to let the admin change `userPrincipalName` with `mail` or something else for example

**Comment by stonith404** [comment]
I've tried to add the email attribute configuration variable in the `stonith404/pingvin-share:development` image. @RatCornu would you mind to test it and let me know if it works. I don't use LDAP because of that I can't test it.

**Comment by RatCornu** [comment]
I'll be quite busy in the next few days but I'll try as soon as possible thanks!

**Comment by WolverinDEV** [comment]
@stonith404 sorry for the late response.  
That's actually a good find.  

> But it would be nice if the email gets mapped from the LDAP, do you think this is difficult to implement?
Well, the reason I mapped the email initially was because of email notifications. Fixing this would probably involve comparing the email of the created/retrieved user entities with the LDAP email attribute. If there is a mismatch, we update the user.  
  
I can make a PR in the next few days.

**Comment by WolverinDEV** [comment]
This should be fixed and can be closed now :)
