### ISSUE TITLE
🐛 Bug Report: App URL not working

### ISSUE THREAD

**Issue by Nos4893** [stonith404/pingvin-share#690]
### 👟 Reproduction steps

I changed the App URL inside of the configuration to something like "http://example.com" but most of the Copy Link dialogs show localhost:3000 instead of http://example.com

### 👍 Expected behavior

It should use the App URL 

### 👎 Actual Behavior

It uses the current window URL

**Comment by stonith404** [comment]
This behavior is expected. Pingvin Share uses the URL you are currently accessing. The App URL is only utilized in scenarios where the application cannot determine the current URL.

**Comment by Nos4893** [comment]
That's unfortunate, cause i am using pingvin share inside of a iFrame, and was able to use the app url to go to a entirely different site than the one actually hosting pingvin share

**Comment by TurtleException** [comment]
Could that be fixed by using `window.top.location.origin` instead of `window.location.origin`?

**Comment by stonith404** [comment]
@Nos4893 Could you share a bit more about why you’re running Pingvin Share in an iframe?

**Comment by stonith404** [comment]
Sorry for my late response.

> window.top.location.origin

This isn't possible because of the Same-Origin Policy. 

Since this appears to be a very specific use case, I would recommend forking the repository and modifying the logic to use the app URL instead of `window.location.origin`. Adding configuration options for such niche scenarios would overcrowd the settings page.

**Comment by stonith404** [comment]
Let me know if you need any help to do these changes.
