### ISSUE TITLE
🚀 Feature: Text sharing

### ISSUE THREAD

**Issue by m-mattia-m** [stonith404/pingvin-share#702]
### 🔖 Feature description

Sometimes I want to share a text like a code snipped, URLs or something else. Therefore it would be great if pingvin-share is able to do this. It should also have a few options to style the text with markdown, code or only plaintext. A important functionality is that the content is encrypted.

### 🎤 Pitch

There is often the situation when I want to share an encrypted text. I found a few options for this, but all of them have disadvantages (not encrypted, storage, no formatting, ugly UI and more). Another reason to implement it in pingvin-share is that you have only one application to maintain and update, which saves you time and effort. I came across these issues: #145, #487, #161 and all of them want the same.  

However, you wrote that you want to keep pingvin-share as simple as possible, but I think it would be a great extension. I've checked the database schema and I think it would be possible to add a new column to the `share` table with the name `kind: file | text`. I would encrypt the text client side (if the user wants this) and send a base64-encoded text to the backend and store the share in the `description` field.

Taking my points above into consideration, I think it wouldn't be a huge change. The biggest change would be the frontend.

What do you think? Do you still don't want this feature, or could I implement it and make a PR in the next few weeks?

**Comment by stonith404** [comment]
I understand your use case and why this feature could be useful. However, my main goal for Pingvin Share is to focus purely on file sharing and keep it as simple as possible. With simple as possible I don't mean that I only want to implement features that are easy to implement but features that are out of scope of the project. Adding text-sharing functionality, even if it seems small, could lead to more feature requests and make the project grow in directions I don’t want.

I often refer to Nextcloud. While I admire what they’ve built, I sometimes feel it has too many features that are out of scope like video calls, which makes it less focused. With Pingvin Share, I want to avoid this and keep it streamlined for file sharing only.


> There is often the situation when I want to share an encrypted text. I found a few options for this, but all of them have disadvantages (not encrypted, storage, no formatting, ugly UI and more). 

This sounds like the perfect opportunity to create your own text sharing service :) I've started Pingvin Share also because I didn't find any solution that I like.

I hope you understand my decision.
